@startuml
queue MessageBroker

folder User {
    node UserService
    database UserDb
    UserService -> UserDb
}
User -(0)- MessageBroker

folder BankAccount {
    node BankAccountService
    database BankAccountDb
    BankAccountService -> BankAccountDb
}
BankAccount -(0)- MessageBroker

folder Transaction {
    node TransactionService
    database TransactionDb
    TransactionService -> TransactionDb
}
Transaction -(0)- MessageBroker

folder Frontend {
    node WebapiService
    database WebapiDb
    WebapiService -> WebapiDb
}
MessageBroker -0)- Frontend
@enduml